### ISSUE TITLE
Expand 'documentations' section.

### ISSUE THREAD

**Issue by Agger1995** [Xitric/BicepLearningPath#1]
I think we need to add a point in the 'Documentation' section, detailing explicit usage of some (if not most) decorators.
This includes:
- `@description('')`
  - **Note:** From next release of Bicep, the usage of `@description('')` is expanded to include variables and resources.
  - https://github.com/Azure/bicep/issues/1665
- `@minLength('')`
- `@maxLength('')`

**Comment by Xitric** [comment]
Add a comment about existing resources being treated similarly to any other resource in terms of file structure.

Also add a reference to all Bicep decorators for parameter constraints (can we find a pretty list?).

**Comment by Xitric** [comment]
All requested changes have now been implemented.
